"""两步验证的「选择接收方式」页(``/ap/mfa/new-otp``)。

亚马逊在无法向卖家手机发短信时,会先插一个方式选择页:三个单选(WhatsApp / 打电话 /
认证器应用)加一个提交按钮,**第一项默认选中**。正常流程要点第三项才会进到紫鸟熟悉
的那个验证码输入页。

这里钉的不是「能不能点对」,而是**点错的后果**:前两项会给卖家真实手机发 WhatsApp
或直接打电话。所以提交前有一道**否定断言** —— 即使正向匹配认错了,也不会走到那条
分支上去。
"""

from __future__ import annotations

import pytest

from ziniao_automation.workflows.amazon_login import (
    _LOGIN_PATHS,
    _OTP_METHOD_PATH,
    AmazonLoginAdvancer,
)

CA = "https://sellercentral.amazon.ca"

# 截图里三个选项的原文（2026-09-02，秦登美切到加拿大站时出现）。
WHATSAPP = "发送 WhatsApp 消息至我的号码（以 559 结尾）"
PHONE_CALL = "给尾号为 559 的手机号打电话"
AUTHENTICATOR = "输入认证器应用程序生成的一次性密码"


def test_the_chooser_is_recognised_as_a_login_page() -> None:
    """不加进白名单的话，这一页根本不会被当成登录页。

    ``is_supported_login_url`` 是**精确集合匹配**，``/ap/mfa`` 不覆盖
    ``/ap/mfa/new-otp``。
    """

    assert _OTP_METHOD_PATH in _LOGIN_PATHS
    assert AmazonLoginAdvancer.is_supported_login_url(
        f"{CA}/ap/mfa/new-otp?ie=UTF8&arb=808885cd-34cc-44b5-91fd-607d42a896d3"
    )


def test_an_unknown_mfa_subpath_is_still_refused() -> None:
    """按前缀放行等于替没见过的页面做主张；未知子路径仍然交人工。"""

    assert not AmazonLoginAdvancer.is_supported_login_url(f"{CA}/ap/mfa/something-else")


@pytest.mark.parametrize(
    "label",
    [
        AUTHENTICATOR,
        "Enter the one-time password generated by your authenticator app",
        "TOTP",
    ],
)
def test_the_authenticator_option_is_matched(label: str) -> None:
    assert AmazonLoginAdvancer._otp_method_authenticator.search(label)


@pytest.mark.parametrize(
    "label",
    [
        WHATSAPP,
        PHONE_CALL,
        "Text me a code",
        "Call me",
        "Send a code to my phone",
        "向我的邮箱发送验证码",
    ],
)
def test_every_delivery_option_is_refused(label: str) -> None:
    """这条断言保护的是卖家的手机。

    它是**否定**判据：提交前确认「当前选中的这一项不是投递渠道」。所以它宁可
    过宽也不能过窄——过宽只是转人工，过窄是真的给卖家发消息或打电话。
    """

    assert AmazonLoginAdvancer._otp_method_delivery.search(label)


@pytest.mark.parametrize("label", [AUTHENTICATOR, "authenticator app"])
def test_the_authenticator_option_is_not_mistaken_for_a_delivery_channel(
    label: str,
) -> None:
    """否定判据不能误伤唯一那条能走通的路，否则这一页永远转人工。"""

    assert not AmazonLoginAdvancer._otp_method_delivery.search(label)


@pytest.mark.parametrize("label", [WHATSAPP, PHONE_CALL])
def test_a_delivery_option_is_not_mistaken_for_the_authenticator(label: str) -> None:
    assert not AmazonLoginAdvancer._otp_method_authenticator.search(label)


def test_the_dispatch_asserts_before_it_submits() -> None:
    """顺序是承重的：先选、再复核、最后才提交。

    源码里这三步的先后不能被后来的改动打乱——先点提交再复核就等于没有保护。
    """

    import inspect

    body = inspect.getsource(AmazonLoginAdvancer._choose_authenticator_otp_method)
    select = body.index("_SELECT_OTP_METHOD")
    recheck = body.index("checked[0]")
    guard = body.index("_otp_method_delivery")
    submit = body.index("submits[0].click()")
    assert select < recheck < guard < submit, "必须先选中、复核、否定断言，最后才提交"


def test_the_dispatch_requires_exactly_one_match_each_way() -> None:
    """歧义一律转人工：匹配到 0 项或多项都不许猜。"""

    import inspect

    body = inspect.getsource(AmazonLoginAdvancer._choose_authenticator_otp_method)
    assert "len(wanted) != 1" in body
    assert "len(checked) != 1" in body
    assert "len(submits) != 1" in body
    # 每一条歧义分支都要走人工，而不是回退成「继续试试」。
    assert body.count("HumanAuthRequired") >= 6
